apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-postgres
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar-postgres
  template:
    metadata:
      labels:
        app: sonar-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: POSTGRES_USER
          value: sonar
        - name: POSTGRES_PASSWORD
          value: sonar
        - name: POSTGRES_DB
          value: sonarqube
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-postgres
  namespace: sonarqube
spec:
  selector:
    app: sonar-postgres
  ports:
  - port: 5432
