version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ECR_REPO: my-app
    EKS_CLUSTER: my-eks-cluster

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Build Docker image
      - docker build -t $ECR_REPO .
      - docker tag $ECR_REPO:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest

  post_build:
    commands:
      - echo Push image to ECR
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
      - echo Deploy to EKS
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER
      - sed -i "s|IMAGE_URI|$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest|g" deployment.yml
      - kubectl apply -f deployment.yml
      - kubectl apply -f service.yml
