apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: default
spec:
  storageClassName: gp3-wffc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

