port 1194
proto udp
dev tun

ca ca.crt
cert server.crt
key server.key

tls-server
tls-version-min 1.3
dh none

tls-groups X25519MLKEM768:SecP256r1MLKEM768

client-config-dir /etc/openvpn/ccd
script-security 2
client-connect /etc/openvpn/zta-check.sh

cipher AES-256-GCM
data-ciphers AES-256-GCM
data-ciphers-fallback AES-256-GCM

verify-client-cert require
remote-cert-tls client

server 10.8.0.0 255.255.255.0
topology subnet
keepalive 10 120

persist-key
persist-tun

verb 4

