[Interface]
PrivateKey = cDp8rZ8uETuW+TdTQrX/6P6dqv20YSNK7laY5SDOklU=
Address = 10.20.0.2/32

[Peer]
PublicKey = pLwLR/vJOIOERDT6wkcfiYraMbsrZ8kowf0xFxEK/XY=
Endpoint = 10.8.0.1:51820
AllowedIPs = 10.20.0.1/32
PersistentKeepalive = 25
