[Interface]
PrivateKey = +LrCv4R0+cLz6sbt5M5QEFNa3EEPQlxVPdCYDLvgs1E=
Address = 10.20.0.1/24
ListenPort = 51820

PostUp = iptables -A INPUT -i wg0 -j ACCEPT
PostUp = iptables -A FORWARD -i wg0 -o tun0 -j ACCEPT
PostUp = iptables -A FORWARD -i tun0 -o wg0 -m state --state RELATED,ESTABLISHED -j ACCEPT

PostDown = iptables -D INPUT -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -o tun0 -j ACCEPT
PostDown = iptables -D FORWARD -i tun0 -o wg0 -m state --state RELATED,ESTABLISHED -j ACCEPT

[Peer]
PublicKey = pLwLR/vJOIOERDT6wkcfiYraMbsrZ8kowf0xFxEK/XY=
AllowedIPs = 10.20.0.2/32
