apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
#  storageClassName: gp3-wffc
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  
  resources:
    requests:
      storage: 5Gi
